instaLens/infographic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import crawled, crawling_loading, find_unfollow_list, show_liked_stats, getInput, display_users

app_name = 'infographic'

urlpatterns = [
    path('', getInput, name='input'), #유저 입력 받는 창
    path('crawled/<str:user_account>/', crawled, name='crawled'), # 크롤링 및 출력 창
    path('loading/<str:user_account>/', crawling_loading, name='crawling_loading'), # 크롤링 및 출력 창
    path('display/unfollow/<str:user_account>/', find_unfollow_list, name='find_unfollow_list'), # 언팔 출력 창
    path('display/stats/<str:user_account>/', show_liked_stats, name='show_liked_stats'), # 시각화 출력 창
    path('display/', display_users, name ='user_overview'), #데이터베이스 저장 확인
    path('unfollow-list/<str:user_account>/', find_unfollow_list, name='find_unfollow_list')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

instaLens/instaLens/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('infographic.urls'))
]

instaLens/infographic/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class User(models.Model): #나의 데이터
    user_account = models.CharField(max_length=30, default='no_account', verbose_name="사용자 인스타 아이디") #나의 아이디
    created_at = models.DateTimeField(default = timezone.now, verbose_name="크롤링 시간") #크롤링 저장 시간

    def __str__(self):
        return f"{self.user_account}"
    
class Friendships(models.Model): #친구의 데이터
    insta_id = models.CharField(max_length=30, verbose_name="인스타 아이디") #친구들의 아이디
    user_account = models.ForeignKey(User, related_name='friendships', on_delete=models.CASCADE) #나의 아이디
    is_following = models.BooleanField(default=False, verbose_name="팔로잉 여부")
    is_follower = models.BooleanField(default=False, verbose_name="팔로워 여부")
    liked_count = models.IntegerField(default=0, verbose_name="좋아요 횟수")
    created_at = models.DateTimeField(default = timezone.now, verbose_name="크롤링 시간") #크롤링 저장 시간

    def __str__(self):
        return f"{self.insta_id}"

instaLens/infographic/views.py
import io
import os

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from matplotlib_venn import venn2

from .insta_tracker import get_data  # 크롤러 import
from .models import User, Friendships


def getInput(request: HttpRequest) -> HttpResponse:
    message = ""
    user_account = ""
    if request.method == 'POST':
        user_account = request.POST.get('username')
        if user_account:
            return HttpResponseRedirect(reverse('infographic:crawled', args=[user_account]))
        else:
            message = "계정 이름을 입력하세요."
    return render(request, 'account_input.html', {'message': message, 'user_account':user_account})

def crawled(request: HttpRequest, user_account: str) -> HttpResponse:
    # 인스타그램 임시 로그인 아이디 정보
    username = ""
    password = ""

    failure_message = []
    '''
    liked_users(dict) - {key : friend name}, {value : 좋아요 수}
    followers(list) - friend name
    followings(list) - friend name
    '''
    try:
        liked_users, followers, followings = get_data(username, password, user_account) or ({}, {}, {})
    except Exception as e:
        failure_message.append(f"크롤링 중 오류 발생\n세부 오류 내용: {str(e)}")
        return render(request, 'crawled_result.html', {'message': failure_message})
    '''
    >> ???? models.py에 정의되어 있는거 아닌가요?
    
    DB 구조
    [User]
    - user_account (사용자 인스타 아이디)
    - created_at (크롤링 날짜)
    [Friendships]
    - insta_id (친구의 아이디)
    - user_account (Foreign - 사용자 인스타 아이디)
    - is_following (팔로잉 여부)
    - is_follower (팔로워 여부)
    - liked_count (좋아요 횟수)
    - created_at (크롤링 날짜)
    '''
    user, created = User.objects.update_or_create(
        user_account = user_account,
        defaults= {
            'created_at': timezone.now()
                  }
        )

    if liked_users:
        for insta_id, liked_count in liked_users.items():
            is_follower = insta_id in followers
            is_following = insta_id in followings
            if insta_id != user_account:
                Friendships.objects.create(
                    insta_id = insta_id,
                    user_account = user,
                    liked_count = liked_count,
                    is_follower = is_follower,
                    is_following = is_following,
                    created_at = user.created_at
                )
    else:
        failure_message.append("게시글이 없습니다. 따라서 Like Stats 내용이 없을 수 있습니다.")

    all_instas = followers.union(followings)  # followers와 followings의 모든 insta_id
    if all_instas:
        print(f"Total Insta ID to check: {len(all_instas)}")
        for insta_id in all_instas:
            is_follower = insta_id in followers
            is_following = insta_id in followings
            
            if (liked_users and insta_id not in liked_users) or (not liked_users):  # liked_users에 포함되지 않은 경우
                Friendships.objects.create(
                    insta_id = insta_id,
                    user_account = user,
                    liked_count = 0,
                    is_follower = is_follower,
                    is_following = is_following,
                    created_at = user.created_at
                )
    else:
        failure_message.append('팔로워나 팔로잉이 없습니다. Follow Tracker 나 Like Stats 내용이 없을 수 있습니다.')
    failure_message.append("크롤링이 완료되었습니다. Follow Tracker 나 Like Stats 탭을 확인해보세요")
    return render(request, 'crawled_result.html', {'message': failure_message, 'user_account': user_account})

def crawling_loading(request, user_account):
    # 크롤링 없이 랜딩 페이지 테스트 함수
    message = []
    message.append("테스트 중입니다.")
    message.append("게시글이 없습니다. 따라서 Like Stats 내용이 없을 수 있습니다.")
    message.append("팔로워나 팔로잉이 없습니다. Follow Tracker 나 Like Stats 내용이 없을 수 있습니다.")
    message.append("크롤링이 완료되었습니다. Follow Tracker 나 Like Stats 탭을 확인해보세요")
    return render(request, 'crawled_result.html', {'message': message, 'user_account': user_account})

def createDatabase(request):
    users = User.objects.all()
    friendships = Friendships.objects.all()
    users_df = pd.DataFrame(list(users.values()))
    friendships_df = pd.DataFrame(list(friendships.values()))
    data = pd.merge(friendships_df, users_df, on='user_account', how='inner')
    grouped = data.groupby('user_account').agg(list).reset_index()

# 24.10.16 건현, 상훈, 서하
def find_unfollow_list(request, user_account):
    data = request.session.get('data')  # 세션에서 data 가져오기

    try:
        # DB에서 팔로워 팔로잉 조회해서 언팔할 리스트 뽑기
        users = User.objects.all()
        friendships = Friendships.objects.all()
        users_df = pd.DataFrame(list(users.values()))
        friendships_df = pd.DataFrame(list(friendships.values()))
        # 각 데이터프레임의 컬럼명 출력
        print("Users DataFrame Columns:")
        print(users_df.columns.tolist())  # users_df의 컬럼명 리스트 출력

        print("\nFriendships DataFrame Columns:")
        print(friendships_df.columns.tolist())  # friendships_df의 컬럼명 리스트 출력
                # User와 Friendships 데이터를 병합해서 `data` 생성
        data = pd.merge(friendships_df, users_df, left_on='user_account_id', right_on='id', how='inner')
    except Exception as e:
        print(f"An error occurred: {str(e)}")
        return render(request, 'myapp/error.html', {'error': str(e)})

    plt.switch_backend('Agg')  # GUI 백엔드를 비활성화

    # 상훈님 밴 다이어그램
    following_set = set(data[(data['user_account'] == user_account) & (data['is_following'])]['insta_id'])
    follower_set = set(data[(data['user_account'] == user_account) & (data['is_follower'])]['insta_id'])
    
    venn = venn2([following_set, follower_set], 
                 set_labels=('Following', 'Follower'),
                 set_colors=('purple', 'orange')
    )
    plt.title(f'Venn Diagram of Following and Follower Status for {user_account}')
    
    # 그래프를 파일로 저장
    venn_image_path = os.path.join(settings.BASE_DIR, 'infographic/static/images/visualization', 'venn_output.png')
    plt.savefig(venn_image_path)  # 이미지 파일로 저장
    # 템플릿에 전달할 이미지 URL
    venn_plot_url = os.path.join(settings.STATIC_URL, 'images/visualization/venn_output.png')
    
    # 총 팔로잉 및 팔로워 수 시각화
    user_accounts = data.groupby('user_account').agg(
        total_following=('is_following', 'sum'),
        total_follower=('is_follower', 'sum')
    ).reset_index()

    # 막대그래프 생성
    user_accounts.set_index('user_account').plot(
        kind='bar', 
        figsize=(10, 6),
        color = ['#1f77b4', '#ff7f0e']
    )
    plt.title('Total Following and Follower Count per User Account')
    plt.xlabel('User Account')
    plt.ylabel('Count')
    plt.xticks(rotation=45)
    plt.legend(title='Account Type', labels=['Total Following', 'Total Follower'])
    plt.tight_layout()  # 레이아웃 조정
    
    # 그래프를 파일로 저장
    bar_image_path = os.path.join(settings.BASE_DIR, 'infographic/static/images/visualization', 'bar_output.png')
    plt.savefig(bar_image_path)  # 이미지 파일로 저장
    # 템플릿에 전달할 이미지 URL
    bar_plot_url = os.path.join(settings.STATIC_URL, 'images/visualization/bar_output.png')
    
    # 언팔 목록 테이블
    unfollowed_friends = data[(data['is_following'] == True) & (data['is_follower'] == False)]
    unfollowed_friend_ids = unfollowed_friends['insta_id'].unique()

    # DataFrame으로 변환
    unfollowed_friends_df = pd.DataFrame(unfollowed_friend_ids, columns=['Unfollowed Friends'])

    n_columns = 3
    max_length = int(np.ceil(len(unfollowed_friends_df) / n_columns))
    split_data = []

    for i in range(n_columns):
        col_data = unfollowed_friends_df.iloc[i * max_length : (i + 1) * max_length].reset_index(drop=True)

        while len(col_data) < max_length:
            col_data = pd.concat([col_data, pd.DataFrame([['']], columns=['Unfollowed Friends'])], ignore_index=True)
        
        split_data.append(col_data)

    combined_df = pd.concat(split_data, axis=1)

    # 테이블 시각화
    plt.figure(figsize=(8, 4))
    plt.axis('tight')
    plt.axis('off')

    table = plt.table(cellText=combined_df.values,
                    colLabels=None,  
                    cellLoc='center', loc='center')

    # 스타일 조정
    table.auto_set_font_size(False)
    table.set_fontsize(12) 
    table.scale(1.5, 1.5)  

    # 셀 색상 설정
    for (i, j), cell in table.get_celld().items():
        cell.set_fontsize(12)  
        cell.set_facecolor('#FFFFFF')  

    # 이미지 저장
    img = io.BytesIO()  
    plt.savefig(img, format='png')  
    img.seek(0)


    # 그래프를 파일로 저장
    table_image_path = os.path.join(settings.BASE_DIR, 'infographic/static/images/visualization', 'table_output.png')
    plt.savefig(table_image_path)  # 이미지 파일로 저장
    # 템플릿에 전달할 이미지 URL
    table_plot_url = os.path.join(settings.STATIC_URL, 'images/visualization/table_output.png')


    #print(plot_url , "최종 전달 url")

# DB에서 팔로워 팔로잉 조회 해서 언팔할 리스트 뽑기
    df = pd.DataFrame(data)

    # 각 조합별로 그룹화
    groups = {
        "Not Following and Not Followed": df[(df['is_following'] == False) & (df['is_follower'] == False)],
        "Following but Not Followed": df[(df['is_following'] == True) & (df['is_follower'] == False)],
        "Not Following but Followed": df[(df['is_following'] == False) & (df['is_follower'] == True)],
        "Following and Followed": df[(df['is_following'] == True) & (df['is_follower'] == True)]
    }
    # 파이 차트를 그리기
    plt.figure(figsize=(16, 12))

    # 각 그룹에 대해 좋아요 횟수에 따른 그룹화
    for i, (label, group_data) in enumerate(groups.items()):
        if group_data.empty:
            continue  # 그룹이 비어 있으면 스킵

        # 각 사용자 계정에 대한 파이 차트를 그리기
        for j, (account, account_data) in enumerate(group_data.groupby('user_account')):

instaLens/infographic/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Insta-Lens{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/apexcharts.css' %}">
    <link rel="stylesheet" href="{% static 'css/tooplate-mini-finance.css' %}">
    <link rel="stylesheet" href="{% static 'font/bootstrap-icons.woff' %}">
    <link rel="stylesheet" href="{% static 'font/bootstrap-icons.woff2' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
    <!-- JS 파일은 body 태그 끝에 추가 -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/apexcharts.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

instaLens/infographic/templates/crawled_result.html
{% extends 'base.html' %}
{% block title %}Insta-Lens{% endblock %}
{% block content %}
{% load static %}  
<!--
Used Tooplate 2135 Mini Finance
https://www.tooplate.com/view/2135-mini-finance
-->

    </head>
     
    <body>
        <header class="navbar sticky-top flex-md-nowrap">
            <div class="col-md-3 col-lg-3 me-0 px-3 fs-6">
                <a class="navbar-brand" href="">
                    <img src="{% static 'images/logo.png' %}" class="img-fluid" width="35" height="35" alt="">
                    5sTeam
                </a>
            </div>
        </header>

        <div class="container-fluid">
            <div class="row">
                <nav id="sidebarMenu" class="col-md-3 col-lg-3 d-md-block sidebar collapse">
                    <div class="position-sticky py-4 px-3 sidebar-sticky">
                        <ul class="nav flex-column h-100">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'infographic:input' %}">
                                    <i class="bi-house-fill me-2"></i>
                                    Welcome
                                </a>
                            </li>

                            <li class="nav-item">
                                {% if user_account %}
                                <a class="nav-link" href="{% url 'infographic:find_unfollow_list' user_account %}">
                                    <i class="bi-person me-2"></i>
                                    Follow Tracker
                                </a>
                                {% else %}
                                    <a class="nav-link" href="">
                                        <i class="bi-person me-2"></i>
                                        Follow Tracker
                                    </a>
                                {% endif %}
                            </li>

                            <li class="nav-item">
                                {% if user_account %}
                                <a class="nav-link" href="{% url 'infographic:show_liked_stats' user_account %}">
                                    <i class="bi-heart-fill me-2"></i>
                                    Like Stats
                                </a>
                                {% else %}
                                    <a class="nav-link" href="">
                                        <i class="bi-heart-fill me-2"></i>
                                        Like Stats
                                    </a>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                </nav>

                <main class="main-wrapper col-md-9 ms-sm-auto py-4 col-lg-9 px-md-4 border-start">
                    <div class="title-group mb-3">
                        <h1 class="h1 mb-0">Crawled Result Message</h1>
                    </div>


                    <div class="row my-4">
                        <div class="col-lg-12">
                            <div class="custom-block custom-block-contact">
                                {% if message %}
                                    {% for text in message %}
                                        <h6 class="mb-4">{{ text }}</h6>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <footer class="site-footer">
                        <div class="container">
                            <div class="row">
                                
                                <div class="col-lg-12 col-12">
                                    <p class="copyright-text">Templete Copyright © Mini Finance 2048 
                                    - Design: <a rel="sponsored" href="https://www.tooplate.com" target="_blank">Tooplate</a></p>
                                </div>

                            </div>
                        </div>
                    </footer>
                </main>

            </div>
        </div>
    </body>
</html>{% endblock %}

instaLens/infographic/templates/show_liked_stats.html
{% extends 'base.html' %}
{% block title %}Insta-Lens{% endblock %}
{% block content %}
{% load static %}  
<!--
Used Tooplate 2135 Mini Finance
https://www.tooplate.com/view/2135-mini-finance
-->
<style>
    th{
            text-align: center;
        }
        h5{
            text-align: center;
        }
</style>
    </head>
    
    <body>
        <header class="navbar sticky-top flex-md-nowrap">
            <div class="col-md-3 col-lg-3 me-0 px-3 fs-6">
                <a class="navbar-brand" href="">
                    <img src="{% static 'images/logo.png' %}" class="img-fluid" width="35" height="35" alt="">
                    5sTeam
                </a>
            </div>
        </header>

        <div class="container-fluid">
            <div class="row">
                <nav id="sidebarMenu" class="col-md-3 col-lg-3 d-md-block sidebar collapse">
                    <div class="position-sticky py-4 px-3 sidebar-sticky">
                        <ul class="nav flex-column h-100">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'infographic:input' %}">
                                    <i class="bi-house-fill me-2"></i>
                                    Welcome
                                </a>
                            </li>

                            <li class="nav-item">
                                {% if user_account %}
                                <a class="nav-link" href="{% url 'infographic:find_unfollow_list' user_account %}">
                                    <i class="bi-person me-2"></i>
                                    Follow Tracker
                                </a>
                                {% else %}
                                    <a class="nav-link" href="">
                                        <i class="bi-person me-2"></i>
                                        Follow Tracker
                                    </a>
                                {% endif %}
                            </li>

                            <li class="nav-item">
                                {% if user_account %}
                                <a class="nav-link active" href="{% url 'infographic:show_liked_stats' user_account %}">
                                    <i class="bi-heart-fill me-2"></i>
                                    Like Stats
                                </a>
                                {% else %}
                                    <a class="nav-link" href="">
                                        <i class="bi-heart-fill me-2"></i>
                                        Like Stats
                                    </a>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                </nav>

                <main class="main-wrapper col-md-9 ms-sm-auto py-4 col-lg-9 px-md-4 border-start">
                    <div class="title-group mb-3">
                        <h1 class="h1 mb-0">Like Statistic Result</h1>
                        <!-- {% if message %}
                            <h6 style="color:red">{{message}}</h6>
                        {% else %}
                            <small class="text-muted">Analyzed recent 10 posts</small>
                        {% endif %}-->
                    </div>

                    <div class="row my-4">
                        <div class="col-lg-12">
                            <div class="custom-block bg-white">
                                <div class="tab-content" id="myTabContent">
                                    <div class="tab-pane fade show active" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
                                        <h6 class="mb-4">Title</h6>
                                        <!-- 시각화 차트 -->
                                        <div>
                                            <h5>좋아요 비율 분석</h5>
                                            <table>
                                                <th>팔로잉 중에 좋아요 눌러주는 사람, 안눌러주는 사람 파이 차트</th>
                                                <th>팔로워 중에 좋아요 눌러주는 사람, 안눌러주는 사람 파이 차트
                                                </th>
                                                <tr>
                                                    <td><img class = "graph_img" src="{{ liked_following_url }}" alt="vendiagram" width="90%" height="auto"></td>
                                                    <td><img class = "graph_img" src="{{ liked_follower_url }}" alt="vendiagram" width="90%" height="auto"></td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <footer class="site-footer">
                        <div class="container">
                            <div class="row">
                                
                                <div class="col-lg-12 col-12">
                                    <p class="copyright-text">Templete Copyright © Mini Finance 2048 
                                    - Design: <a rel="sponsored" href="https://www.tooplate.com" target="_blank">Tooplate</a></p>
                                </div>

                            </div>
                        </div>
                    </footer>
                </main>

            </div>
        </div>
    </body>
</html>
{% endblock %}

instaLens/infographic/templates/show_unfollow_list.html
{% extends 'base.html' %}
{% block title %}Insta-Lens{% endblock %}
{% block content %}
{% load static %}  
<!--
Used Tooplate 2135 Mini Finance
https://www.tooplate.com/view/2135-mini-finance
-->

    <style>
        .graph_img{
            width: 90%;
            height: auto;
        }
        th{
            text-align: center;
        }
        h5{
            text-align: center;
        }
    </style>
    </head>
    
    <body>
        <header class="navbar sticky-top flex-md-nowrap">
            <div class="col-md-3 col-lg-3 me-0 px-3 fs-6">
                <a class="navbar-brand" href="">
                    <img src="{% static 'images/logo.png' %}" class="img-fluid" width="35" height="35" alt="">
                    5sTeam
                </a>
            </div>
        </header>

        <div class="container-fluid">
            <div class="row">
                <nav id="sidebarMenu" class="col-md-3 col-lg-3 d-md-block sidebar collapse">
                    <div class="position-sticky py-4 px-3 sidebar-sticky">
                        <ul class="nav flex-column h-100">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'infographic:input' %}">
                                    <i class="bi-house-fill me-2"></i>
                                    Welcome
                                </a>
                            </li>

                            <li class="nav-item">
                                {% if user_account %}
                                <a class="nav-link active" href="{% url 'infographic:find_unfollow_list' user_account %}">
                                    <i class="bi-person me-2"></i>
                                    Follow Tracker
                                </a>
                                {% else %}
                                    <a class="nav-link" href="">
                                        <i class="bi-person me-2"></i>
                                        Follow Tracker
                                    </a>
                                {% endif %}
                            </li>

                            <li class="nav-item">
                                {% if user_account %}
                                <a class="nav-link" href="{% url 'infographic:show_liked_stats' user_account %}">
                                    <i class="bi-heart-fill me-2"></i>
                                    Like Stats
                                </a>
                                {% else %}
                                    <a class="nav-link" href="">
                                        <i class="bi-heart-fill me-2"></i>
                                        Like Stats
                                    </a>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                </nav>

                <main class="main-wrapper col-md-9 ms-sm-auto py-4 col-lg-9 px-md-4 border-start">
                    <div class="title-group mb-3">
                        <h1 class="h1 mb-0">Follow Tracker Result</h1>
                        {% if message %}
                            <h6 style="color:red">{{message}}</h6>
                        {% endif %}
                    </div>
                    
                    <!-- 시각화 부분 -->
                    <div class="row my-4">
                        <div class="col-lg-12">
                            <div class="custom-block bg-white">
                                <div class="tab-content" id="myTabContent">
                                    <div class="tab-pane fade show active" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
                                        <h6 class="mb-4">Follow & Following</h6>
                                        <div>
                                            <div id ="visualization">
                                            <h5>내 인스타 구성원 비율</h5>
                                                <!--언팔할 파이차트 이미지-->
                                                <table width="100%" height="auto">
                                                    <th><span>팔로워 팔로잉 벤다이어그램</span></th>
                                                    <th>Unfollowed Friends List</th>
                                                    <tr>
                                                        <!--팔로워 팔로잉 벤다이어 그램-->
                                                        <td><img class = "graph_img" src="{{ venn_plot_url }}" alt="vendiagram" width="auto" height="auto"></td>
                                                        <!--정확한 팔로워, 팔로잉 수 (축약형 대체), 막대그래프-->                                                        
                                                        <td><img class = "graph_img" src="{{ bar_plot_url }}" alt="막대그래프" width="auto" height="auto"></td>
                                                    </tr>
                                                </table>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="custom-block custom-block-exchange">
                        <h5 class="mb-4">Recommended Unfollow Lists</h5>
                        <div>
                            <h5>나를 언팔로우 하는 계정</h5>
                            <img src="{{ table_plot_url }}" alt="unfollow table" width="auto" height="auto">
                        </div>
                        {% for recommneded in unfollow_list %}
                        <div class="d-flex align-items-center border-bottom pb-3 mb-3">
                            <div class="d-flex align-items-center">
                                
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                    <!--디테일 차트-->
                    <div class="custom-block bg-white">
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
                                <h6 class="mb-4">Follow & Following Detail</h6>
                                <div>
                                    <div id ="visualization">
                                    <h5>팔로잉 팔로워별 좋아요 횟수 비교 분석</h5>
                                        <img src = "{{ pie_chart_url }}" alt="unfollow table detail" width="90%" height="auto">                     
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                    <footer class="site-footer">
                        <div class="container">
                            <div class="row">
                                
                                <div class="col-lg-12 col-12">
                                    <p class="copyright-text">Templete Copyright © Mini Finance 2048 
                                    - Design: <a rel="sponsored" href="https://www.tooplate.com" target="_blank">Tooplate</a></p>
                                </div>

                            </div>
                        </div>
                    </footer>
                </main>

            </div>
        </div>
    </body>
</html>
{% endblock %}